services:
  - type: web
    name: my-backend
    env: node
    plan: free
    buildCommand: "npm install"
    startCommand: "npm start"
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGODB_URI
        sync: false   # Set in Render dashboard
      - key: JWT_SECRET
        sync: false   # Set in Render dashboard